upgrade to Symfony 6.4
shopsys/JsFormValidatorBundle pull request #4
Opened 2024-09-27 09:21 UTC by vitek-rostislav

2024-09-30 09:01 UTC, TomasLudvik requested changes

2024-09-30 09:01 UTC, TomasLudvik commented on package.json
> +    "webpack-notifier": "^1.15.0"
I wonder if these should not be updated as well

2024-09-30 09:01 UTC, TomasLudvik commented on composer.json
> +        "symfony/html-sanitizer": "*",
I do not feel good about having dependency version as `*`.

2024-09-30 09:35 UTC, vitek-rostislav commented on composer.json
> +        "symfony/html-sanitizer": "*",
On a call, we agreed on keeping it as is

2024-09-30 09:57 UTC, vitek-rostislav commented on package.json
> +    "webpack-notifier": "^1.15.0"
I reverted the unneeded changes in `package.json` and updated all the existing dependencies to their latest versions :wink:

2024-10-01 09:38 UTC, TomasLudvik approved these changes

2024-10-01 11:46 UTC, pk16011990 approved these changes

2024-10-07 14:24 UTC, merged